import { createApp } from "vue";
import "./style.css";
import App from "./App.vue";
import Antd from "ant-design-vue";
import "ant-design-vue/dist/antd.css";
import "@/assets/base.css";
import mitt from "mitt";
const app = createApp(App);
app.config.globalProperties.$mitt = mitt();
app.use(Antd).mount("#app");
